# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 88b60c1310f18ee234f0ed97062ba07dc824c300d5ba2d442a90e476fdb2670f1f045dc9277ff5cad3ca044337cb83b4a4e2550abefec6096574dc3a3145d747

test:
  secret_key_base: 6c3a756aa755a6acb7b932fa663f7bd1da969bb844900ea1c4ee79088b3fb2e03c41ff3fba261c9f6c8a98c2ce06fa6be576da89dfcbd3b34f55ebd06e09c638

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
